### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by miguelkennedy** [blueToolz/openLibreReader-iOS-#1]
Hi!

I'm having some issues compiling the app in Xcode 9.

Can you add instructions on how to compile the project or can you add an ipa to the "releases" section of this repo?

Thanks!

**Comment by GerrietR** [comment]
Hi Miguel,

I was faced with the same problems, too!

Meanwhile, I managed to get my own working openLibreReader for iOS (at least on the simulator for now).

After some trial and error, I came up with the following podfile:

```
platform :ios, '10.0'
use_frameworks!

target 'openLibreReader' do
    pod 'Socket.IO-Client-Swift', '~> 12.1.2' # Or latest version
    pod 'MMWormhole', '~> 2.0.0'
    pod 'Charts'
    target 'openLibreReaderWidget' do
        inherit! :search_paths
    end
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end
end
```
I've added a platform to silence a message on `pod install` and updated `Socket.IO-Client-Swift` because of a compile error.
`Charts` was somehow missing, but the current version 3.0.4 seems to be ok.
The post install step stops Xcode from complaining about a wrong Swift version.

To actually run the app it was important to update the app group identifiers in `openLibreReader/AppDelegate.m` and `openLibreReaderWidget/TodayViewController.m´ to your own app group.

Hope this helps!
Gerriet

**Comment by miguelkennedy** [comment]
Thanks, GerrietR.

Much appreciated it!

I'm going to give it another try following your instructions ;)

**Comment by SandraK82** [comment]
fixed dependencies it,
you need the translation processor bartycrouch ([https://github.com/Flinesoft/BartyCrouch]) to build without errors
